# get api_id & api_hash from my.telegram.org
api_id: '20681550'
api_hash: 'e7568e1e1100838d24d89a3a7bef305c'
# 13 digit channel id startswith - like -111.......
dump_id: '-1002341600799'
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: '1BVtsOJMBu7meqSLeNRpbPyr6XLlx7CxU1wvbou0D2lysV9RrACuDbu12pKyg_fIoTkkeQL8WyldCHVxUlNk3T4TZI0CmdJgZIURS9-N8F09GtaUoo8q1CnDxxtLTkQhyvxD3IkC_DhsuxEXY1e1_mEM730HKSQeCHvsBlZreFn_Zjn9u1ptmpLoYgZH2xPBzv4-Jh5YFmff0oKWe_afjmkoMCTitSkBCUcJGqrxLoPKCsd-EWilSRxOAS0HWgFRslWcKN3EgfTJCImdw6OkIeJPolfOX3F896D4ytF-qoY9p764u9Mke61wAHE1WwpXltKWnJ7GwBuW6mvUUux5c5NzcJuuP85U='
